"""add content to post

Revision ID: 22edf326ae8a
Revises: 4bb07f14e7f4
Create Date: 2026-08-27 13:00:52.555943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22edf326ae8a'
down_revision = '4bb07f14e7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
